name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: omidtavakoly
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#7C3AED&color_dots=#EBEDF0,#C4B5FD,#A78BFA,#7C3AED,#4C1D95
            dist/github-contribution-grid-snake-dark.svg?color_snake=#C4B5FD&color_dots=#21262D,#312E81,#4C1D95,#7C3AED,#A78BFA

      - name: Publish Contribution Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
